config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'

  resources :products, only: [:index, :show, :new, :create, :destroy]
  # get 'products', to: 'products#index'
  # get 'products/:id', to: 'products#show'
  # delete '/products/:id', to: 'products#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @time = Time.now
    @name = "alex"
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end

  def new
    @product = Product.new
  end

  def create
    product = Product.new(product_params)
    product.save
    redirect_to products_path
  end

  def destroy
    # 1. find the correct product
    product = Product.find(params[:id])
    # 2. destroy it
    product.destroy
    # 3. redirect to index page
    redirect_to products_path
  end

  def product_params
    params.require(:product).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WagonHunt</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Welcome to my website!</h1>
<p><%= @time %></p>

<h3><%= @name %></h3>

app/views/products/index.html.erb
<h1>All our products!</h1>

<ul>
  <% @products.each do |product| %>
    <li><%= link_to product.name, product_path(product) %></li>
  <% end %>
</ul>

<%= link_to 'Add new Product', new_product_path %>

app/views/products/new.html.erb
<h1>Create new product</h1>

<%= form_for @product do |f| %>
  <%= f.text_field :name %>
  <%= f.submit %>
<% end %>

app/views/products/show.html.erb
<h1>Product <%= @product.name %></h1>

<%= link_to "Back to Home", products_path %>

<%= link_to "Remove this product", product_path(@product), method: :delete %>